// lib
import "../styles/globals.css"
import type { AppProps } from "next/app"
import Head from "next/head"
import { RecoilRoot } from "recoil"
import { useCallback, useEffect } from "react"

// components
import Layout from "src/components/layout"

/**
 * Wrapper
 */

const MyApp = ({ Component, pageProps }: AppProps) => {
  type consoleType = "log" | "debug" | "warn" | "error"
  const consoleKey: consoleType[] = ["log", "debug", "warn", "error"]
  if (process.env.NEXT_PUBLIC_API_URL !== "local") {
    consoleKey.map((key: consoleType) => {
      console[key] = () => {}
    })
  }

  return (
    <>
      <Head>
        <title>ks typing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <RecoilRoot>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </RecoilRoot>
    </>
  )
}

export default MyApp
